version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -q -U api-key-service@oplabs-local-web.iam -d api-key-service',
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    volumes:
      - ./setup-local-db.sql:/docker-entrypoint-initdb.d/setup-local-db.sql

  api-key-service:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: api-key-service
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=api-key-service
    healthcheck:
      test: wget localhost:7330/healthz -q -O - > /dev/null 2>&1
    ports:
      - 7330:7330
    depends_on:
      postgres:
        condition: service_healthy
