version: '3.8'

services:
  postgres:
    profiles:
      - dependencies
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -q -U dapp-console-api@oplabs-local-web.iam -d dapp-console',
        ]
    volumes:
      - ./setup-local-db.sql:/docker-entrypoint-initdb.d/setup-local-db.sql
    ports:
      - '5432:5432'

  redis:
    profiles:
      - dependencies
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    volumes:
      - redis_data:/data/redis
    ports:
      - 6479:6379

  api-queue-redis:
    profiles:
      - dependencies
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    volumes:
      - api_queue_redis_data:/data/redis
    ports:
      - 6579:6379

  gateway-redis:
    profiles:
      - dependencies
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    volumes:
      - gateway_redis_data:/data/redis
    ports:
      - 6679:6379

  api:
    profiles:
      - app
    build:
      context: ../../
      dockerfile: Dockerfile
      target: dapp-console-api
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - GATEWAY_REDIS_URL=redis://gateway-redis:6379
      - API_QUEUE_REDIS_URL=redis://api-queue-redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dapp-console
      - MIGRATE_DB_USER=dapp-console-api@oplabs-local-web.iam
      - DB_USER=dapp-console-api@oplabs-local-web.iam
    healthcheck:
      test: curl http://0.0.0.0:7300/api/v0/healthz
    volumes:
      - ../../certs/extra-ca-certificates.crt:/usr/local/share/ca-certificates/extra-ca-certificates.crt
    ports:
      - 7400:7300
    depends_on:
      redis:
        condition: service_healthy

  api-processor:
    profiles:
      - app
    build:
      context: ../../
      dockerfile: Dockerfile
      target: dapp-console-api-processor
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - GATEWAY_REDIS_URL=redis://gateway-redis:6379
      - API_QUEUE_REDIS_URL=redis://api-queue-redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dapp-console
      - MIGRATE_DB_USER=dapp-console-api@oplabs-local-web.iam
      - DB_USER=dapp-console-api@oplabs-local-web.iam
    volumes:
      - ../../certs/extra-ca-certificates.crt:/usr/local/share/ca-certificates/extra-ca-certificates.crt
    ports:
      - 7340:7340
    depends_on:
      api-queue-redis:
        condition: service_healthy

volumes:
  redis_data:
  gateway_redis_data:
  api_queue_redis_data:
